# Generated by Django 3.2.9 on 2021-11-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederset',
            name='feeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeder_app.feeder'),
        ),
    ]
