# Generated by Django 3.2.9 on 2021-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder_app', '0002_feederset_feeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederset',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
